name: Testing
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: '3.9'
    steps:
    - uses: checkout@v2
      with:
        fetch-depth: ‘2’

    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.7
    - name: Install Packages
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest==7.1.2
        python -m pip install coverage
    - name: Test with pytest
      run: |
        coverage run --source=PyXAB -m pytest
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v3
